### ISSUE TITLE
nebula对比实验

### ISSUE THREAD

**Issue by QwQxwqQwQ** [SenseCore/transom-checkpoint-engine#2]
请问论文中提到的Transom与Nebula的对比实验具体是在什么环境下执行的？可否提供Nebula的源码及测试脚本？谢谢

**Comment by EastInsure** [comment]
感谢关注，Nebula不开源，我们拿不到他的源码和测试脚本，我们从Nebula的官方介绍上拿到了他们的测试数据，链接如下：
https://learn.microsoft.com/en-us/azure/machine-learning/reference-checkpoint-performance-for-large-models?view=azureml-api-2&tabs=PYTORCH
我们构造了相同参数量的大模型训练任务以及checkpoint大小，与其公开的数据进行了相关对比。
